### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by ybouazza** [eeddaann/Bucket-brigade#4]
Hi, It works now, and it suggests me the different configurations.
`WHEN I choose the second for example, here is what i get : 

Can you help me to find the cause ?

choose config: (0,2..,20). x to exit 2
$@==################################################################################==@$
Traceback (most recent call last):

  File "/Users/Younes-BOUAZZAOUI/Downloads/Bucket-brigade-master 2/interface.py", line 69, in <module>
    "$@==#### {} -> {} seconds.####==@$".format(str(config_lst[int(user_input)]), str(round(config_lst[int(user_input)].run_config(),4))))

  File "/Users/Younes-BOUAZZAOUI/Downloads/Bucket-brigade-master 2/interface.py", line 24, in run_config
    data = pack(self.capacity, self.picksize)

  File "/Users/Younes-BOUAZZAOUI/Downloads/Bucket-brigade-master 2/heuristic.py", line 26, in pack
    y = pulp.LpVariable.dicts('BinUsed', range(maxBins), lowBound=0, upBound=1, cat=pulp.LpInteger)

AttributeError: module 'pulp.pulp' has no attribute 'LpInteger'

Thanks a lot

**Comment by eeddaann** [comment]
Fixed in 434f0acfb2dd9b0c2a5538fd67fec4e477974034

seems like were a breaking change in PuLP which caused this issue
